parameters:

services:
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    App\:
        resource: "../src/"
    App\EventListener\JwtRequestListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request }
